// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {AI} from '../models';
import {backend} from '../models';
import {entity} from '../models';
import {connections} from '../models';
import {search} from '../models';

export function CopyFile(arg1:string):Promise<void>;

export function CreateFile(arg1:string,arg2:string):Promise<void>;

export function CreateFolder(arg1:string,arg2:string):Promise<void>;

export function CreateGoogleDoc(arg1:string,arg2:string):Promise<void>;

export function CutFile(arg1:string):Promise<void>;

export function DisconnectGoogle():Promise<void>;

export function ExecuteAICommands(arg1:Array<AI.Command>):Promise<Array<Error>>;

export function GetAICommands(arg1:string,arg2:string):Promise<Array<AI.Command>>;

export function GetAppIcon(arg1:string):Promise<string>;

export function GetFolderContents(arg1:string):Promise<Array<backend.FileItem>>;

export function GetFolderTree(arg1:string,arg2:number):Promise<entity.FolderNode>;

export function GetGoogleEmail():Promise<string>;

export function GetHomeDirectory():Promise<string>;

export function GetHomeFolders():Promise<Array<backend.Folder>>;

export function GoUpDirectory(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function HandleGoogleCallback(arg1:string):Promise<void>;

export function HasClipboardContent():Promise<boolean>;

export function IsGoogleConnected():Promise<boolean>;

export function ListGmailMessages():Promise<Array<connections.GmailMessage>>;

export function ListGoogleDocs():Promise<Array<connections.GoogleFile>>;

export function MoveFile(arg1:string,arg2:string):Promise<void>;

export function OpenApplication(arg1:string):Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function PasteFile(arg1:string):Promise<void>;

export function ReadFileContent(arg1:string):Promise<string>;

export function RecommendMove(arg1:string,arg2:string):Promise<AI.RecommendMoveResponse>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function Search(arg1:string,arg2:string):Promise<Array<search.SearchResult>>;

export function SearchFilenames(arg1:string,arg2:string):Promise<Array<search.SearchResult>>;

export function ShareFile(arg1:string,arg2:string):Promise<void>;

export function SortByDate(arg1:Array<backend.FileItem>,arg2:boolean):Promise<Array<backend.FileItem>>;

export function SortByName(arg1:Array<backend.FileItem>,arg2:boolean):Promise<Array<backend.FileItem>>;

export function SortBySize(arg1:Array<backend.FileItem>,arg2:boolean):Promise<Array<backend.FileItem>>;

export function StartGoogleLogin():Promise<string>;

export function SummarizeDirectory(arg1:string):Promise<AI.SummarizeResponse>;

export function TrashFile(arg1:string):Promise<void>;

export function UnZip(arg1:string):Promise<void>;

export function Zip(arg1:string):Promise<void>;
