// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {search} from '../models';

export function CopyFile(arg1:string):Promise<void>;

export function CutFile(arg1:string):Promise<void>;

export function GetAppIcon(arg1:string):Promise<string>;

export function GetFolderContents(arg1:string):Promise<Array<backend.FileItem>>;

export function GetHomeDirectory():Promise<string>;

export function GetHomeFolders():Promise<Array<backend.Folder>>;

export function Greet(arg1:string):Promise<string>;

export function HasClipboardContent():Promise<boolean>;

export function OpenApplication(arg1:string):Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function PasteFile(arg1:string):Promise<void>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function Search(arg1:string,arg2:string):Promise<Array<search.SearchResult>>;

export function SearchFilenames(arg1:string,arg2:string):Promise<Array<search.SearchResult>>;

export function SortByDate(arg1:Array<backend.FileItem>,arg2:boolean):Promise<Array<backend.FileItem>>;

export function SortByName(arg1:Array<backend.FileItem>,arg2:boolean):Promise<Array<backend.FileItem>>;

export function SortBySize(arg1:Array<backend.FileItem>,arg2:boolean):Promise<Array<backend.FileItem>>;

export function TrashFile(arg1:string):Promise<void>;
