// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyFile(arg1) {
  return window['go']['main']['App']['CopyFile'](arg1);
}

export function CutFile(arg1) {
  return window['go']['main']['App']['CutFile'](arg1);
}

export function DisconnectGoogle() {
  return window['go']['main']['App']['DisconnectGoogle']();
}

export function ExecuteAICommands(arg1) {
  return window['go']['main']['App']['ExecuteAICommands'](arg1);
}

export function GetAICommands(arg1, arg2) {
  return window['go']['main']['App']['GetAICommands'](arg1, arg2);
}

export function GetAppIcon(arg1) {
  return window['go']['main']['App']['GetAppIcon'](arg1);
}

export function GetFolderContents(arg1) {
  return window['go']['main']['App']['GetFolderContents'](arg1);
}

export function GetGoogleEmail() {
  return window['go']['main']['App']['GetGoogleEmail']();
}

export function GetHomeDirectory() {
  return window['go']['main']['App']['GetHomeDirectory']();
}

export function GetHomeFolders() {
  return window['go']['main']['App']['GetHomeFolders']();
}

export function GoUpDirectory(arg1) {
  return window['go']['main']['App']['GoUpDirectory'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HandleGoogleCallback(arg1) {
  return window['go']['main']['App']['HandleGoogleCallback'](arg1);
}

export function HasClipboardContent() {
  return window['go']['main']['App']['HasClipboardContent']();
}

export function IsGoogleConnected() {
  return window['go']['main']['App']['IsGoogleConnected']();
}

export function ListGoogleDocs() {
  return window['go']['main']['App']['ListGoogleDocs']();
}

export function OpenApplication(arg1) {
  return window['go']['main']['App']['OpenApplication'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function PasteFile(arg1) {
  return window['go']['main']['App']['PasteFile'](arg1);
}

export function ReadFileContent(arg1) {
  return window['go']['main']['App']['ReadFileContent'](arg1);
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2);
}

export function Search(arg1, arg2) {
  return window['go']['main']['App']['Search'](arg1, arg2);
}

export function SearchFilenames(arg1, arg2) {
  return window['go']['main']['App']['SearchFilenames'](arg1, arg2);
}

export function SortByDate(arg1, arg2) {
  return window['go']['main']['App']['SortByDate'](arg1, arg2);
}

export function SortByName(arg1, arg2) {
  return window['go']['main']['App']['SortByName'](arg1, arg2);
}

export function SortBySize(arg1, arg2) {
  return window['go']['main']['App']['SortBySize'](arg1, arg2);
}

export function StartGoogleLogin() {
  return window['go']['main']['App']['StartGoogleLogin']();
}

export function TrashFile(arg1) {
  return window['go']['main']['App']['TrashFile'](arg1);
}
